language: node_js
os: linux
dist: bionic
node_js:
  - node
  - lts/*
services:
  - postgresql # for @tussle/state-postgres
before_script:
  - psql -c 'create database tussle_test;' -U postgres
  - psql -f ./packages/state-postgres/create_table.psql -U postgres

