version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

workflows:
  workflow:
    jobs:
      - run-tests

jobs:
  run-tests:
    docker:
      - image: circleci/node:latest
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tussle_test
    environment:
      POSTGRES_CONNECT_STRING: postgres://postgres:postgres@localhost/tussle_test
    steps:
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: install postgresql client
          command: |
            sudo apt-get update
            sudo apt-get install postgresql-client
      - checkout
      - restore_cache:
          key: v1-deps={{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package.json" }}
      - run: yarn run build
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: create database tables for @tussle/state-postgres tests
          command: psql -h localhost -p 5432 -f ./packages/state-postgres/create_table.psql -d tussle_test -U postgres
      - run:
          name: Unit tests with coverage
          command: yarn run coverage
      - coveralls/upload
